//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFS.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenralSetting
    {
        public int GSId { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public int Fee { get; set; }
        public string Facebook { get; set; }
        public string Indeed { get; set; }
        public string Linkedin { get; set; }
        public string Youtube { get; set; }
        public string Pintrest { get; set; }
    }
}
